name = "SplineMakie"
uuid = "5f9b0a48-72a2-44e0-9813-fb3859179609"
authors = ["Hans Würfel <git@wuerfel.io> and contributors"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
